removing validating blocking single-AZ ES clusters
cloudposse/terraform-aws-elasticsearch pull request #159
Opened 2023-04-19 17:49 UTC by jacob-hudson

## what

Removing errant validation preventing the creation of Amazon OpenSearch Service ElasticSearch (ES) or OpenSearch (OS) clusters which live in a single Available Zone on Amazon Web Services (AWS)

Simple Process:
- You merge this PR
- You release a new version
- We can create clusters which live in one AZ
- Everyone wins

## why

Development and testing clusters may not want or need two or more Availability Zones for cost (among other reasons, but FinOps - saving money - is important) 

## references
https://github.com/cloudposse/terraform-aws-elasticsearch/issues/158

Identical errors in internal company environment

2023-04-19 19:39 UTC, milldr commented
valid values for `zone_awareness_config` are only 2 and 3 for the Terraform resource. Why remove that check?

- terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain 
- relevant module resource attribute: https://github.com/cloudposse/terraform-aws-elasticsearch/blob/3125d5a76a4c3a7021aec48459086de6aac35b01/main.tf#L155-L160

2023-04-19 20:19 UTC, jacob-hudson commented
> valid values for `zone_awareness_config` are only 2 and 3 for the Terraform resource. Why remove that check?
> 
> * terraform documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain
> * relevant module resource attribute: https://github.com/cloudposse/terraform-aws-elasticsearch/blob/3125d5a76a4c3a7021aec48459086de6aac35b01/main.tf#L155-L160

You guys do not pin module versions to TF versions, meaning we could need the latest module (wg for EBS GP3) and not care about which `aws` provider version

Maybe remove the check and let AWS respond with an error a la GraphQL?

2023-04-19 20:22 UTC, Nuru requested changes
This seems unnecessary to me. I would need to see added testing before I would approve this.

Users should be able to set `zone_awareness_enabled` to `false` and leave `availability_zone_count` unset and defaulted to 2, or set to 2 if the configuration of the root module makes leaving it unset too difficult.

2023-04-19 21:09 UTC, jacob-hudson commented
> This seems unnecessary to me. I would need to see added testing before I would approve this.
> 
> Users should be able to set `zone_awareness_enabled` to `false` and leave `availability_zone_count` unset and defaulted to 2, or set to 2 if the configuration of the root module makes leaving it unset too difficult.

Working on this, give me a few

2023-04-19 21:55 UTC, jacob-hudson commented
Interesting point:

Would there ever be a chance you would want Zone Awareness disabled with more than 1 AZ?

2023-04-20 01:52 UTC, Nuru commented on variables.tf
> +    condition     = contains([2, 3], var.availability_zone_count) && var.zone_awareness_enabled == "true"
**INVALID TERRAFORM**: Variable validation [conditions can refer only to the containing variable](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#input-variable-validation).

2023-06-02 14:37 UTC, ManuelMueller1st commented
Can't we add 1 as a valid count? This seems unnecessarily complex to me.

2023-10-25 21:47 UTC, closed without merging